apexTestsMinCoverageOrgWide: 75
developmentBranch: development
devHubAlias: ''
devHubInstanceUrl: https://login.salesforce.com
devHubUsername: ''
installPackagesDuringCheckDeploy: false
manualActionsFileUrl: ''
newTaskNameRegex: ''
newTaskNameRegexExample: ''
sharedDevSandboxes: false
useDeltaDeployment: true
useSmartDeploymentTests: false
allowedOrgTypes:
  - sandbox
deploymentPlan:
  packages: []
